Creating a vector

In [5]:
#One dimensional array
import numpy as np

vector_row = np.array([1,2,4])

creating a matrix

In [10]:
#multidimensional array
import numpy as np

matrix = np.array([
    [0, 3],
    [1, 0],
    [0, 6]
])
print(matrix)


[[0 3]
 [1 0]
 [0 6]]


creating  a sparse matrix

In [14]:
import numpy as np
from scipy import sparse


matrix = np.array([
    [0, 3],
    [1, 0],
    [0, 6]
])

matix_sparse =sparse.csr_matrix(matrix)
print(matix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 2)>
  Coords	Values
  (0, 1)	3
  (1, 0)	1
  (2, 1)	6


selecting/accesing elements


In [25]:
import numpy as np 

matrix = np.array([
    [0, 3],
    [1, 0],
    [0, 6]
])
vector = np.array([1,2,4])

print(vector[2])
print(matrix[1,1])
matrix.shape


4
0


(3, 2)

operations on martix

In [27]:
import numpy as np 

matrix = np.array([
    [0, 3],
    [1, 0],
    [0, 6]
])
#creating function to add 100

add_100 = lambda i: i + 100

#vectorized function
vec_add_100 = np.vectorize(add_100)

vec_add_100(matrix)

print(vec_add_100(matrix))


[[100 103]
 [101 100]
 [100 106]]
[[  0 300]
 [100   0]
 [  0 600]]


Average, Variance, and Standard Deviation

In [3]:
import numpy as np 

matrix = np.array([
    [0, 3],
    [1, 0],
    [0, 6]
])
#average 
print(np.mean(matrix))
#variance
print(np.var(matrix))
#std
print(np.std(matrix))

1.6666666666666667
4.888888888888888
